[build]
  publish = "_site"
  command = "npm run build"

[[headers]]
  for = "/asset/**/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/**/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/css/*.css"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/asset/js/*.js"
    [headers.values]
    Cache-Control = "public, max-age=3600"

# Adicione esta parte:
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
