backend:
  name: git-gateway
  branch: main

media_folder: "asset/photos"
public_folder: "/asset/photos"

collections:
  - name: "fotos"
    label: "Posts com Imagens"
    folder: "posts-photos"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "main/post-photos.html",
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Palavras-chave", name: "keyword", widget: "string" }
      - { label: "Imagem de Capa", name: "cover", widget: "image" }
      - {
          label: "Miniatura",
          name: "thumbnail",
          widget: "image",
          media_folder: "/asset/photos/thumbnail",
          public_folder: "/asset/photos/thumbnail",
        }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Texto", name: "body", widget: "markdown" }

  - name: "textos"
    label: "Posts de Texto"
    folder: "posts-blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "main/post-blog.html",
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Palavras-chave", name: "keyword", widget: "string" }
      - {
          label: "Imagem de Capa",
          name: "cover",
          widget: "image",
          media_folder: "/asset/blog",
          public_folder: "/asset/blog",
        }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Texto", name: "body", widget: "markdown" }
